[package]
name = "jwt"
version = "0.1.0"
authors = ["Drazen Urch <github@drazenur.ch>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
rustc-serialize = "0.3"
openssl = "^0.9"
time = "0.1.35"
log = "0.3.6"
